# Site settings
title: andreas offenhaeuser
description: resume and portfolio
favicon: /assets/img/avatar.JPG
baseurl: https://anoff.io
google_analytics:

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Andreas Offenhaeuser
  title: Cloud Solution Architect
  address: Stuttgart, Germany
  email: offenhaeuser#gmail.com
  link: http://anoff.io
  weibo:
  github: anoff
  linkedin: anoff
  twitter: '@an0xff'
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: German
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Beginner
  programmingSkills:
    - skill1:
      name: nodeJS
      percentage: 100%
    - skill2:
      name: JavaScript
      percentage: 90%
    - skill3:
      name: Python
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 30%
